= Small JTA benchmark suite


== Goals

This small webapp is intended to give you a rough feeling about JTA vs resource-local JPA transactions 


== Benchmarking
To run the simulations execute the folowing steps:

. start tomee (if not done yet):
+
----
mvn tomee:start
----

. start the simulation:
+
----
mvn gatling:execute -P perf
---- 
+
[TIP]
====
For the torture mode use:
----
 mvn gatling:execute -Dtorture -P perf
---- 
it will run the simulations for a longer period (~7min instead of 50 sec) with more users simultaneously
====

. access simulation reports in jtabench/target/gatling

. stop tomee
----
mvn tomee:stop
----

NOTE: Each user will perform 100 database operations on each request

== Results
Resulting reports can be accessed on links below:

* http://rmpestano.github.io/jtabench/jtasimulation/index.html[JTA simulation report^]
* http://rmpestano.github.io/jtabench/nonjtasimulation/index.html[NON JTA simulation report^]
* http://rmpestano.github.io/jtabench/jtaandnonjtasimulation/index.html[JTA and NON JTA simulation report^]

the above simulations were ran without torture flag on a core I5(3470) CPU and 8GB RAM using JDK 8(u40).

For now the results are the same for both modes, maybe the simulation needs to be reworked or maybe JTA perform same as non JTA. 

Here is a report generated for torture mode:

http://rmpestano.github.io/jtabench/jtaandnonjtasimulation_torture/index.html[JTA and NON JTA **Torture** simulation report^]

Now we can see some difference in response time where non jta has a slight better performance (as expected)